name: CICD Workflow

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

  build:
    needs: test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

      - name: Build app
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-cicd-artifact
          path: dist/

  deploy_production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Production setup
        uses: ./.github/actions/deploy-to-s3
        with:
          artifact_name: build-cicd-artifact
          environment_name: production
          aws_bucket: ${{ secrets.AWS_S3_BUCKET_MAIN }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_MAIN }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MAIN }}
